

CREATE TABLE USER_DETAIL
(USER_ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
FIRST_NAME VARCHAR2(50) NOT NULL,
LAST_NAME VARCHAR2(50) NOT NULL,
USER_NAME VARCHAR2(100) NOT NULL,
PASSWORD VARCHAR2(50) NOT NULL,
ROLE VARCHAR2(15) DEFAULT 'TEAM MEMBER',
CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
UNIQUE(USER_NAME),
CONSTRAINT PK_USER_ID PRIMARY KEY (USER_ID));

DESC USER_DETAIL;

DROP TABLE USER_DETAIL cascade constraints;
DROP TABLE USER_DETAIL;

INSERT INTO USER_DETAIL(FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,ROLE)VALUES('DHARSHAN','RAVI','dharshanravi@gmail.com','Dharshan03@','ADMIN');
INSERT INTO USER_DETAIL(FIRST_NAME,LAST_NAME,USER_NAME,PASSWORD,ROLE)VALUES('PRIYA','RAVI','priyaravi@gmail.com','Priya24#','ADMIN');

DELETE USER_DETAIL WHERE user_id=2;

SELECT * FROM USER_DETAIL order by user_id;


CREATE TABLE TASK_DETAIL(
TASK_ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
USER_ID NUMBER NOT NULL,
CONSTRAINT FK_ID FOREIGN KEY(USER_ID) REFERENCES USER_DETAIL(USER_ID),
TASK_NAME VARCHAR2(50)NOT NULL,
START_DATE DATE  NOT NULL,
END_DATE DATE  NOT NULL,
TASK_PRIORITY VARCHAR2(18)NOT NULL,
ASSSIGNED_TO VARCHAR2(50)NOT NULL,
CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
ASSIGNED_TO_DATE DATE  NOT NULL,
CONSTRAINT Pk_task_id PRIMARY KEY (TASK_ID));


DESC TASK_DETAIL;
DROP TABLE TASK_DETAIL;

CREATE TABLE TIMESHEET(
TIMESHEET_ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
USER_ID NUMBER NOT NULL,
CONSTRAINT FK_uID FOREIGN KEY(USER_ID) REFERENCES USER_DETAIL(USER_ID),
TASK_ID NUMBER NOT NULL,
CONSTRAINT FK_task1_ID FOREIGN KEY(TASK_ID) REFERENCES TASK_DETAIL(TASK_ID),
SPEND_TIME_HRS NUMBER NOT NULL,
COMMENTS VARCHAR2(200) NOT NULL,
TIMESHEET_FOR_DATE DATE NOT NULL, 
TIMESHEET_UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL,
CONSTRAINT Pk_timesheet_id PRIMARY KEY (TIMESHEET_ID)
);

DROP TABLE TIMESHEET;
DESC TIMESHEET;

CREATE TABLE STATUS(
STATUS_ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
USER_ID NUMBER NOT NULL,
CONSTRAINT FK_userID FOREIGN KEY(USER_ID) REFERENCES USER_DETAIL(USER_ID),
TIMESHEET_ID NUMBER NOT NULL,
CONSTRAINT FKTime_ID FOREIGN KEY(TIMESHEET_ID) REFERENCES TIMESHEET(TIMESHEET_ID),
STATUS VARCHAR2(50) DEFAULT ('NOT APPROVED') NOT NULL,
APPROVED_BY VARCHAR2(100),
STATUS_UPDATE_DATE  DATE DEFAULT SYSDATE NOT NULL,
CONSTRAINT Prk_status_id PRIMARY KEY(STATUS_ID)
);


DESC USER_DETAIL;
DESC task_detail;
DESC TIMESHEET;
DESC STATUS;

COMMIT; 
